categories = {
    "Greetings": {
        "Hola": "Hello",
        "Buenos días": "Good morning",
        "Buenas tardes": "Good afternoon",
        "Buenas noches": "Good evening / Good night",
        "Adiós": "Goodbye",
        "Hasta luego": "See you later",
        "Hasta pronto": "See you soon",
        "Hasta mañana": "See you tomorrow",
        "Nos vemos": "See you",
        "Chao": "Bye",
        "¿Cómo estás?": "How are you?",
        "Estoy bien": "I am fine",
        "¿Qué tal?": "How’s it going?",
        "Mucho gusto": "Nice to meet you",
        "Encantado/a": "Pleased to meet you",
        "Por favor": "Please",
        "Gracias": "Thank you",
        "De nada": "You’re welcome",
        "Lo siento": "I’m sorry",
        "Disculpe": "Excuse me"
    },
    "Transportation": {
        "Coche": "Car",
        "Autobús": "Bus",
        "Tren": "Train",
        "Avión": "Airplane",
        "Bicicleta": "Bicycle",
        "Moto": "Motorcycle",
        "Barco": "Boat",
        "Camión": "Truck",
        "Metro": "Subway",
        "Taxi": "Taxi",
        "Helicóptero": "Helicopter",
        "Tranvía": "Tram",
        "Patinete": "Scooter",
        "Carro": "Car (alt.)",
        "Ferry": "Ferry",
        "Caminata": "Walk",
        "Monopatín": "Skateboard",
        "Remolque": "Trailer",
        "Vagón": "Wagon",
        "Cohete": "Rocket"
    },
    "School Objects": {
        "Libro": "Book",
        "Lápiz": "Pencil",
        "Bolígrafo": "Pen",
        "Cuaderno": "Notebook",
        "Mochila": "Backpack",
        "Pizarra": "Board",
        "Borrador": "Eraser",
        "Regla": "Ruler",
        "Sacapuntas": "Pencil sharpener",
        "Carpeta": "Folder",
        "Tijeras": "Scissors",
        "Pegamento": "Glue",
        "Calculadora": "Calculator",
        "Marcador": "Marker",
        "Mapa": "Map",
        "Escritorio": "Desk",
        "Silla": "Chair",
        "Agenda": "Planner",
        "Libreta": "Small notebook",
        "Goma": "Rubber eraser"
    },
    "Food & Drinks": {
        "Agua": "Water",
        "Leche": "Milk",
        "Pan": "Bread",
        "Queso": "Cheese",
        "Carne": "Meat",
        "Pollo": "Chicken",
        "Pescado": "Fish",
        "Huevo": "Egg",
        "Arroz": "Rice",
        "Frijoles": "Beans",
        "Manzana": "Apple",
        "Plátano": "Banana",
        "Naranja": "Orange",
        "Uva": "Grape",
        "Café": "Coffee",
        "Té": "Tea",
        "Jugo": "Juice",
        "Sopa": "Soup",
        "Ensalada": "Salad",
        "Postre": "Dessert"
    },
    "Family": {
        "Madre": "Mother",
        "Padre": "Father",
        "Hermano": "Brother",
        "Hermana": "Sister",
        "Abuelo": "Grandfather",
        "Abuela": "Grandmother",
        "Tío": "Uncle",
        "Tía": "Aunt",
        "Primo": "Cousin (male)",
        "Prima": "Cousin (female)",
        "Hijo": "Son",
        "Hija": "Daughter",
        "Nieto": "Grandson",
        "Nieta": "Granddaughter",
        "Esposo": "Husband",
        "Esposa": "Wife",
        "Sobrino": "Nephew",
        "Sobrina": "Niece",
        "Padrastro": "Stepfather",
        "Madrastra": "Stepmother"
    },
    "Colors": {
        "Rojo": "Red",
        "Azul": "Blue",
        "Verde": "Green",
        "Amarillo": "Yellow",
        "Negro": "Black",
        "Blanco": "White",
        "Gris": "Gray",
        "Marrón": "Brown",
        "Rosa": "Pink",
        "Naranja": "Orange",
        "Violeta": "Violet",
        "Celeste": "Sky blue",
        "Beige": "Beige",
        "Dorado": "Gold",
        "Plateado": "Silver",
        "Turquesa": "Turquoise",
        "Fucsia": "Fuchsia",
        "Verde claro": "Light green",
        "Verde oscuro": "Dark green",
        "Morado": "Purple"
    },
    "Numbers": {
        "Uno": "One",
        "Dos": "Two",
        "Tres": "Three",
        "Cuatro": "Four",
        "Cinco": "Five",
        "Seis": "Six",
        "Siete": "Seven",
        "Ocho": "Eight",
        "Nueve": "Nine",
        "Diez": "Ten",
        "Once": "Eleven",
        "Doce": "Twelve",
        "Trece": "Thirteen",
        "Catorce": "Fourteen",
        "Quince": "Fifteen",
        "Dieciséis": "Sixteen",
        "Diecisiete": "Seventeen",
        "Dieciocho": "Eighteen",
        "Diecinueve": "Nineteen",
        "Veinte": "Twenty"
    },
    "Common Phrases": {
        "¿Dónde está...?": "Where is...?",
        "¿Cuánto cuesta?": "How much does it cost?",
        "No entiendo": "I don’t understand",
        "¿Puedes ayudarme?": "Can you help me?",
        "Quiero esto": "I want this",
        "No sé": "I don’t know",
        "Tengo hambre": "I am hungry",
        "Tengo sed": "I am thirsty",
        "Estoy perdido/a": "I am lost",
        "Necesito ir": "I need to go",
        "Está bien": "It’s okay",
        "No importa": "It doesn’t matter",
        "¿Habla inglés?": "Do you speak English?",
        "Claro": "Of course",
        "Por supuesto": "Of course",
        "Tal vez": "Maybe",
        "Nunca": "Never",
        "Siempre": "Always",
        "A veces": "Sometimes",
        "Ahora": "Now"
    },
    "Clothing": {
        "Camisa": "Shirt",
        "Pantalón": "Pants",
        "Zapatos": "Shoes",
        "Sombrero": "Hat",
        "Vestido": "Dress",
        "Falda": "Skirt",
        "Chaqueta": "Jacket",
        "Abrigo": "Coat",
        "Guantes": "Gloves",
        "Bufanda": "Scarf",
        "Calcetines": "Socks",
        "Botas": "Boots",
        "Cinturón": "Belt",
        "Traje": "Suit",
        "Corbata": "Tie",
        "Pijama": "Pajamas",
        "Sandalias": "Sandals",
        "Gafas": "Glasses",
        "Gorra": "Cap",
        "Reloj": "Watch"
    },
    "Nature": {
        "Árbol": "Tree",
        "Flor": "Flower",
        "Hierba": "Grass",
        "Hoja": "Leaf",
        "Montaña": "Mountain",
        "Río": "River",
        "Lago": "Lake",
        "Mar": "Sea",
        "Océano": "Ocean",
        "Playa": "Beach",
        "Sol": "Sun",
        "Luna": "Moon",
        "Estrella": "Star",
        "Nube": "Cloud",
        "Lluvia": "Rain",
        "Nieve": "Snow",
        "Viento": "Wind",
        "Arena": "Sand",
        "Roca": "Rock",
        "Bosque": "Forest"
    }
}

